permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'daniel'

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

postcss:
  cache: false
