permalink: /:title/

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
      prose: true
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'daniel'
      prose: true

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

postcss:
  cache: false

# jekyll-seo-tag properties
description: Daniel's random thoughts mostly related to software engineering
url: https://blog.bitgate.cz
author:
  name: Daniel Kessl
  url: https://blog.bitgate.cz
